src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Approver (SME)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date this Approval Step was initiated.</description>
        <inlineHelpText>The date this Approval Step was initiated.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDelegateFieldAssignmentOnApprvlStep.cls
@isTest
public class TestDelegateFieldAssignmentOnApprvlStep{

	@testSetup
	static void testDataSetup(){
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> exsitingStandardUsers = new List<User>();
        for(Integer i = 1; i < 6; i++) {
            exsitingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert exsitingStandardUsers;
		
		system.debug('#############################################################################');
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
	}

    static testMethod void testDelegateAssignment(){

    	DelegateFieldAssignmentOnApprovalStep.isTest = true;

    	List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);
		User testUser3 = ControlledDocumentTestUtility.getDelegateOfUser(existingStandardUsers.get(1).Id);

		Approval_Step__c step;

		System.runAs(testUser1) {
			Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
			insert controlDoc;

			step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.Id, '1', testUser2.Id);
			insert step;

			////////////////////
			Test.startTest();
			////////////////////

			ControlledDocumentTestUtility.initiateApprovalStep(step.Id);

			////////////////////
			Test.stopTest();
			////////////////////

		}

		System.runAs(testUser3){

			ControlledDocumentTestUtility.approveApprovalStep(step.Id);

		}

		System.assert(true);

    }
    @isTest static void testApprovalStepValidation() {
        DelegateFieldAssignmentOnApprovalStep.isTest = true;
        
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c approvalStep = new Approval_Step__c();
        approvalStep.Correspondence_Document__c = controlDoc.Id;
        approvalStep.Sequence__c = '1';
        approvalStep.Start_Date__c = System.today();
        approvalStep.Due_Date__c = System.today()+1;
        approvalStep.Role_of_Approver__c = 'Approver';
        approvalStep.Assigned_Approver__c = UserInfo.getUserId();
        approvalStep.Approval_Status__c ='Initiated';
        insert approvalStep;
        approvalStep.Due_Date__c = System.today()-1;
        approvalStep.Approval_Status__c = 'Approved';
        try {
            update approvalStep;
        }
        catch(DMLException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));   
        }
    }

}