src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRelatedApprovalStepListController.cls
@isTest
private class TestRelatedApprovalStepListController {

	@testSetup
	static void testDataSetup(){
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> exsitingStandardUsers = new List<User>();
        for(Integer i = 1; i < 6; i++) {
            exsitingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert exsitingStandardUsers;
		
		system.debug('#############################################################################');
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
	}
	
	@isTest static void testNoApprovalSteps() {
		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);
		Test.stopTest();

		System.assertEquals(1, controller.manager.approvalStepSelects.size(), 'The approvalStepSelects list should only include the new row.');
		System.assertEquals(false, controller.editMode);
	}

	@isTest static void testWithExistingApprovalSteps() {
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		Controlled_Document__c otherControlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert new List<Controlled_Document__c>{controlDoc, otherControlDoc};

		newApprovalSteps.add(ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId()));
		newApprovalSteps.add(ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '2', UserInfo.getUserId()));
		newApprovalSteps.add(ControlledDocumentTestUtility.createApprovalStep(otherControlDoc.id, '1', UserInfo.getUserId()));
		insert newApprovalSteps;

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);
		Test.stopTest();

		System.assertEquals(3, controller.manager.approvalStepSelects.size(), 'The approvalStepSelects list should only include the 2 inserted approval steps and the new row.');
		System.assertEquals(false, controller.editMode);
	}

	@isTest static void testEditMode(){
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;
		insert ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);

		Test.startTest();
		controller.editMode();
		Test.stopTest();

		System.assertEquals(true, controller.editMode);
		System.assertEquals(1, controller.manager.ApprovalStepSelects.size(), 'Manager should have removed the last row, leaving only 1 approval step.');
	}

	@isTest static void testReadMode(){
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;
		insert ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);
		controller.editMode();

		Test.startTest();
		controller.readMode();
		Test.stopTest();

		System.assertEquals(false, controller.editMode);
		System.assertEquals(2, controller.manager.ApprovalStepSelects.size(), 'Manager should have readded the last row, leaving 2 approval steps.');
	}

	@isTest static void testSaveTable(){
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;
		insert ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);
		controller.editMode();

		Test.startTest();
		controller.saveTable();
		Test.stopTest();

		System.assertEquals(false, controller.editMode);
		System.assertEquals(2, controller.manager.ApprovalStepSelects.size(), 'Manager should have readded the last row, leaving 2 approval steps.');
	}

	@isTest static void testFailedSaveTable(){
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;
		Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
		step.Office__c = null;
		insert step;
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);
		controller.editMode();

        System.debug('=== controller.editMode: ' + controller.editMode);
		System.debug('=== controller.manager.save(): ' + controller.manager.save());
        
		Test.startTest();
		controller.saveTable();
		Test.stopTest();

        System.debug('=== controller.editMode: ' + controller.editMode);
		System.debug('=== controller.manager.save(): ' + controller.manager.save());

        System.assertEquals(false, controller.editMode);
		System.assertEquals(1, controller.manager.ApprovalStepSelects.size(), 'Manager should have remained in edit mode, leaving only 1 row.');
	}

	@isTest static void testGetExternalReviewRoleName(){
		List<Approval_Step__c> newApprovalSteps = new List<Approval_Step__c>();

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;
		insert ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
		ApexPages.StandardController sc = new ApexPages.StandardController(controlDoc);
		RelatedApprovalStepListController controller = new RelatedApprovalStepListController(sc);
		Test.setCurrentPage(Page.RelatedApprovalStepList);

		Test.startTest();
		controller.getEXTERNAL_REVIEW_ROLE_NAME();
		Test.stopTest();

		System.assertEquals(ControlledDocumentConstants.EXTERNAL_REVIEW_ROLE_NAME, controller.getEXTERNAL_REVIEW_ROLE_NAME());
	}
}