src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <description>The number of business days that elapse after this Approval Step was initiated and before it was completed.</description>
        <inlineHelpText>The number of business days that elapse after this Approval Step was initiated and before it was completed.</inlineHelpText>
        <label>Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Approver (SME)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the ExecSec user assigned to the record.</inlineHelpText>
        <label>ExecSec Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <inlineHelpText>A calculation of the number of days a record has been open. This field is the difference between the ExecSec Start Date and either the current date, or the ExecSec End Date if that field is populated.</inlineHelpText>
        <label>ExecSec Business Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Overdue__c</fullName>
        <description>A calculation of the number of days a record has been open beyond the Due Date. This field is calculated as the number of business days that have passed since the Due Date before the record was marked as closed (i.e., Stage = Closed). If today&apos;s date is still before the Due Date, the field should either be blank or show a 0. Once the record has been closed and has a Date Closed, the calculation should use that field instead of today&apos;s date to calculate the &quot;Days Overdue&quot; field.</description>
        <inlineHelpText>This is a calculation of the number of business days a record has been or was open (i.e., Stage was not Closed) beyond the Due Date.</inlineHelpText>
        <label>Business Days Overdue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Days_Overdue__c</fullName>
        <description>The number of business days that have passed beyond the ExecSec Due Date. If the ExecSec End Date is populated, this field represents the number of business days that passed between the ExecSec Due Date and the ExecSec End Date.</description>
        <inlineHelpText>The number of business days that have passed beyond the ExecSec Due Date. If the ExecSec End Date is populated, this field represents the number of business days that passed between the ExecSec Due Date and the ExecSec End Date.</inlineHelpText>
        <label>ExecSec Days Overdue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExecSec_Due_Date__c</fullName>
        <inlineHelpText>The date by when ExecSec should complete their work on the record. This is generally the day it is sent for signature.</inlineHelpText>
        <label>ExecSec Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_End_Date__c</fullName>
        <inlineHelpText>The date ExecSec completed their work on this record.</inlineHelpText>
        <label>ExecSec End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Start_Date__c</fullName>
        <inlineHelpText>This shows the date that ExecSec begins working on a Controlled Document record, but can be changed by ExecSec users.</inlineHelpText>
        <label>ExecSec Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resources Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional &amp; Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <recordTypes>
        <fullName>Controlled_Document</fullName>
        <active>true</active>
        <description>Record Type for Controlled Documents</description>
        <label>Controlled Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ControlledDocumentTriggerHelperTest.cls
@isTest
public without sharing class ControlledDocumentTriggerHelperTest {
/*
Additional Test coverage for ControlledDocumentTriggerHelper.cls
is found in TestChatterFeedItemTrigger.cls, TestApprovalStepSelectManager.cls,
and TestChatterFileCollaboratorTH
 */
 
	@testSetup
	static void testDataSetup(){
		
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> existingStandardUsers = new List<User>();
        for(Integer i = 1; i < 4; i++) {
            existingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert existingStandardUsers;
		//List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		system.debug('########');
		system.debug(testUser1Standard.id);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		system.debug('############');
		system.debug(existingStandardUsersWithDelegate);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
		
		PermissionSet nonexecSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_User_CRE'];
		insert new PermissionSetAssignment(AssigneeId = testUser1Standard.id, PermissionSetId = nonexecSecPerm.Id);
		
	}

	@isTest
	public static void testExecSecDaysOpen(){
		List<Id> userIds = new List<Id>();
		for (PermissionSetAssignment pa : [
				SELECT Id, AssigneeId
				FROM PermissionSetAssignment
				WHERE PermissionSet.Name Like 'Controlled_Document%'
		]) {
			userIds.add(pa.AssigneeId);
		}
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.Assignee__c = userIds[0];
		controlledDocument.ExecSec_Start_Date__c = Date.newInstance(2018,10,22);
		controlledDocument.ExecSec_End_Date__c = Date.newInstance(2018,10,26);
		controlledDocument.Due_Date__c = Date.newInstance(2018,10,21);

		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT Days_Open__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.Days_Open__c);
	}

	@isTest
	public static void testExecSecDaysOpenGivenNoEndDate(){
		List<Id> userIds = new List<Id>();
		for (PermissionSetAssignment pa : [
				SELECT Id, AssigneeId
				FROM PermissionSetAssignment
				WHERE PermissionSet.Name Like 'Controlled_Document%'
		]) {
			userIds.add(pa.AssigneeId);
		}
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.Assignee__c = userIds[0];
		controlledDocument.ExecSec_Start_Date__c = Date.newInstance(2018,10,22);
		controlledDocument.Due_Date__c = Date.newInstance(2018,10,22);

		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT Days_Open__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.Days_Open__c);
	}

	@isTest
	public static void testExecSecDaysOverdue(){
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.ExecSec_Due_Date__c = Date.newInstance(2018,10,22);
		controlledDocument.ExecSec_End_Date__c = Date.newInstance(2018,10,25);

		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT ExecSec_Days_Overdue__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.ExecSec_Days_Overdue__c);
	}

	@isTest
	public static void testExecSecDaysOverdueGivenNoEndDate(){
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.ExecSec_Due_Date__c = Date.newInstance(2018,10,22);

		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT ExecSec_Days_Overdue__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.ExecSec_Days_Overdue__c);
	}

	@isTest
	public static void testDaysOverdue(){
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.Due_Date__c = Date.newInstance(2018,10,22);


		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT Days_Overdue__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.Days_Overdue__c);
	}

	@isTest
	public static void testDaysOverdueWithExecSecEndDate(){
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.Due_Date__c = Date.newInstance(2018,10,22);
		controlledDocument.ExecSec_End_Date__c = Date.newInstance(2018,10,25);

		Test.startTest();
		insert controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT Days_Overdue__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.Days_Overdue__c);
	}

	@isTest
	public static void testUpdate(){
		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
		controlledDocument.Due_Date__c = Date.today();
		controlledDocument.ExecSec_End_Date__c = Date.today()+1;
		insert controlledDocument;
		
        Approval_Step__c step = new Approval_Step__c();
        step.Sequence__c = '1';
        step.Due_Date__c = Date.today().addDays(7);
        step.Role_of_Approver__c = 'Drafter';
        step.Approval_Status__c = 'Initiated';
        step.Assigned_Approver__c = UserInfo.getUserId();
        step.Correspondence_Document__c = controlledDocument.Id;        
        insert step;
        
		Test.startTest();
        controlledDocument.Assignee__c = UserInfo.getUserId();
        controlledDocument.ExecSec_Start_Date__c = Date.today();
        controlledDocument.Stage__c = 'Concurrence';
		update controlledDocument;
		Test.stopTest();

		Controlled_Document__c modifiedDocument = [SELECT Days_Overdue__c FROM Controlled_Document__c WHERE Id=:controlledDocument.Id];

		System.assertNotEquals(null, modifiedDocument.Days_Overdue__c);
	}

	@isTest
	public static void testUserStageModifyAccess(){
		UserDA userAccessor = new UserDA();
		PermissionSetAssignmentDA permSetAssignmentDA = new PermissionSetAssignmentDA();

		List<PermissionSetAssignment> psa = [
				SELECT Id, AssigneeId
				FROM PermissionSetAssignment
				WHERE PermissionSet.Name = 'Controlled_Document_Tracker_User_CRE'
				AND Assignee.IsActive = true
		];

		User CDTUser;
		for(PermissionSetAssignment pa : psa){
			List<PermissionSetAssignment> userPermissionSetAssignments = permSetAssignmentDA.getPermissionSetAssignmentsForUserId(pa.AssigneeId);
			Boolean userIsExecSec = false;
			for (PermissionSetAssignment permsa : userPermissionSetAssignments){
				if (ControlledDocumentConstants.EXECSEC_USER_PERMISSION_SET_NAMES.contains(permsa.PermissionSet.Name)) {
					userIsExecSec = true;
				}
			}
			if(!userIsExecSec){
				CDTUser = userAccessor.getUserById(pa.AssigneeId);
				break;
			}
		}

		User activeUser = userAccessor.getUserById(UserInfo.getUserId());


		Controlled_Document__c controlledDocument = new Controlled_Document__c();
		System.runAs(activeUser) {
			insert controlledDocument;

			Approval_Step__c step = new Approval_Step__c();
			step.Sequence__c = '1';
			step.Due_Date__c = Date.today().addDays(7);
			step.Role_of_Approver__c = 'Drafter';
			step.Approval_Status__c = 'Initiated';
			step.Assigned_Approver__c = CDTUser.Id;
			step.Correspondence_Document__c = controlledDocument.Id;

			insert step;

		}


		Controlled_Document__c controlledDocument2;

		Test.startTest();

		System.runAs(CDTUser){
			controlledDocument.Stage__c = 'Drafting';
			try{
				update controlledDocument;
			}catch (DmlException e){
				System.debug(e.getMessage());
				System.assert(true);
			}
			controlledDocument2 = new Controlled_Document__c();
			insert controlledDocument2;
		}

		System.runAs(activeUser) {
			try {
				update controlledDocument;
			} catch (DmlException e) {
				System.debug(e.getMessage());
				System.assert(false);
			}

			controlledDocument2.Stage__c = 'Drafting';
			try {
				update controlledDocument2;
			} catch (DmlException e) {
				System.debug(e.getMessage());
				System.assert(true);
			}
		}

		Test.stopTest();

	}
}