src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <inlineHelpText>The type of document represented by the primary file(s) being approved through this record.</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Plan</fullName>
                </value>
                <value>
                    <fullName>AFR</fullName>
                </value>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>ASF: Cost &amp; Capital Plan</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Directive</fullName>
                </value>
                <value>
                    <fullName>E-Gov Reporting</fullName>
                </value>
                <value>
                    <fullName>FISMA</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>GAO Draft Response</fullName>
                </value>
                <value>
                    <fullName>GAO Final Response</fullName>
                </value>
                <value>
                    <fullName>Hazardous Waste Report</fullName>
                </value>
                <value>
                    <fullName>Home-To-Work</fullName>
                </value>
                <value>
                    <fullName>IG Audit</fullName>
                </value>
                <value>
                    <fullName>IG Draft Response</fullName>
                </value>
                <value>
                    <fullName>IG Final Response</fullName>
                </value>
                <value>
                    <fullName>Instructional Letter</fullName>
                </value>
                <value>
                    <fullName>Interagency Agreement</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Lease Prospectus</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>MOU</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health</fullName>
                </value>
                <value>
                    <fullName>OMB Scorecard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <inlineHelpText>The date correspondence received or control started.</inlineHelpText>
        <label>Date Received/Started</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GSA_Action_Required__c</fullName>
        <inlineHelpText>This field indicates the highest-level action required for record closure.</inlineHelpText>
        <label>GSA Action Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Signature/Approval of the Administrator</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of the Deputy Administrator</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of the Chief of Staff</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of the PBS Commissioner</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of the FAS Commissioner</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of the TTS Commissioner</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of H1AA Director</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OAS</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OCFO</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OCIA</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OCIO</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OCM</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OCR</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OGC</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OGP</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OHRM</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OMA</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- OSBU</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of HSSO- TTS</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval of PTT</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R1</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R2</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R3</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R4</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R5</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R6</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R7</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R8</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R9</fullName>
                </value>
                <value>
                    <fullName>Signature/Approval RA- R10</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_External__c</fullName>
        <description>This field indicates whether the file(s) being approved is a response to an outside request or is a GSA initiated document.</description>
        <inlineHelpText>External: Documents responding to request from outside GSA (e.g., congressional response). 
Internal: GSA-initiated documents to fulfill legal, regulatory, or other requirement (e.g., delegations, prospectuses, MOUs, reports).</inlineHelpText>
        <label>Internal/External</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resources Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional &amp; Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Program Review</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>Region</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ApprovalStepDATest.cls
@isTest
public with sharing class ApprovalStepDATest {
	
	@testSetup
	static void testDataSetup(){
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> exsitingStandardUsers = new List<User>();
        for(Integer i = 1; i < 6; i++) {
            exsitingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert exsitingStandardUsers;
		
		system.debug('#############################################################################');
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
	}
	
	@isTest
	public static void getAllInitiatedApprovalStepsWithControlledDocumentId_givenUninitiatedStep_shouldReturnEmptyList(){
		ApprovalStepDA testDA = new ApprovalStepDA();
		User testUser = insertTestUser();
		Controlled_Document__c document = insertControlledDocument(testUser);
		Approval_Step__c step = insertApprovalStep(testUser, document);

		Test.startTest();
		List<Approval_Step__c> steps = testDA.getAllInitiatedApprovalStepsWithControlledDocumentId(document.Id);
		Test.stopTest();

		System.assertEquals(0, steps.size());
	}

	@isTest
	public static void getAllInitiatedApprovalStepsWithControlledDocumentId_givenInitiatedStep_shouldReturnOneStep(){
		ApprovalStepDA testDA = new ApprovalStepDA();
		User testUser = insertTestUser();
		Controlled_Document__c document = insertControlledDocument(testUser);
		Approval_Step__c step = insertInitiatedApprovalStep(testUser, document);

		Test.startTest();
		List<Approval_Step__c> steps = testDA.getAllInitiatedApprovalStepsWithControlledDocumentId(document.Id);
		Test.stopTest();

		System.assertEquals(1, steps.size());
		System.assertEquals(step.Id, steps[0].Id);
	}

	@isTest
	public static void getAllInitiatedApprovalStepsWithControlledDocumentIds_givenInitiatedSteps_shouldReturnTwoSteps(){
		ApprovalStepDA testDA = new ApprovalStepDA();
		User testUser = insertTestUser();
		Controlled_Document__c document1 = insertControlledDocument(testUser);
		Approval_Step__c step1 = insertInitiatedApprovalStep(testUser, document1);
		Controlled_Document__c document2 = insertControlledDocument(testUser);
		Approval_Step__c step2 = insertInitiatedApprovalStep(testUser, document2);

		List<Id> docIds = new List<Id>{
				document1.Id,
				document2.Id
		};

		List<Id> stepIds = new List<Id>{
				step1.Id,
				step2.Id
		};

		Test.startTest();
		List<Approval_Step__c> steps = testDA.getAllInitiatedApprovalStepsWithControlledDocumentIds(docIds);
		Test.stopTest();

		System.assertEquals(2, steps.size());
		System.debug('=== steps: ' +  steps);
		System.debug('=== stepIds: ' +  stepIds);
		
		for (Approval_Step__c s : steps){
			System.debug(s);
			System.assert(stepIds.contains(s.Id));
		}

		List<AggregateResult> maxSteps = testDA.getMaxInitiatedTimeForDocumentIds(docIds);
		System.debug('=== maxSteps: ' +  maxSteps);
		System.assertEquals(2, maxSteps.size());


	}


	private static User insertTestUser(){
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard Platform User'];
		User genericUser = new User(Alias = 'atreides',
		Email='leto@testorg.com',
		User_Region__c = 'Region1',
		EmailEncodingKey='UTF-8',
		LastName='Atreides',
		UserName='leto@testorg.com',
		Division='ADF',
		LanguageLocaleKey='en_US',
		LocaleSidKey='en_US',
		TimeZoneSidKey='America/Los_Angeles',
		ProfileId = p.Id);


		insert genericUser;
		return genericUser;
	}

	private static Controlled_Document__c insertControlledDocument(User u){
		Controlled_Document__c document = new Controlled_Document__c();
		document.Date_Received__c = Date.today();
		document.Internal_External__c = 'External';
		document.GSA_Action_Required__c = 'Other';
		document.Correspondence_Type__c = 'Other';
		document.Stage__c = 'Initiated';
		document.Due_Date__c = Date.today().addDays(30);
		document.Originating_Office__c = 'Other';
		document.Final_Signatory__c = u.Id;

		insert document;
		return document;
	}

	private static Approval_Step__c insertApprovalStep(User u, Controlled_Document__c document){
		Approval_Step__c step = new Approval_Step__c();
		step.Sequence__c = '1';
		step.Due_Date__c = Date.today().addDays(7);
		step.Role_of_Approver__c = 'Drafter';
		step.Approval_Status__c = 'Not Initiated';
		step.Assigned_Approver__c = u.Id;
		step.Correspondence_Document__c = document.Id;

		insert step;
		return  step;
	}

	private static Approval_Step__c insertInitiatedApprovalStep(User u, Controlled_Document__c document){
		Approval_Step__c step = new Approval_Step__c();
		step.Sequence__c = '1';
		step.Due_Date__c = Date.today().addDays(7);
		step.Role_of_Approver__c = 'Drafter';
		step.Approval_Status__c = 'Initiated';
		step.Assigned_Approver__c = u.Id;
		step.Correspondence_Document__c = document.Id;

		insert step;
		return  step;
	}
}