src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Approver (SME)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <inlineHelpText>The type of document represented by the primary file(s) being approved through this record.</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Plan</fullName>
                </value>
                <value>
                    <fullName>AFR</fullName>
                </value>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>ASF: Cost &amp; Capital Plan</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Directive</fullName>
                </value>
                <value>
                    <fullName>E-Gov Reporting</fullName>
                </value>
                <value>
                    <fullName>FISMA</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>GAO Draft Response</fullName>
                </value>
                <value>
                    <fullName>GAO Final Response</fullName>
                </value>
                <value>
                    <fullName>Hazardous Waste Report</fullName>
                </value>
                <value>
                    <fullName>Home-To-Work</fullName>
                </value>
                <value>
                    <fullName>IG Audit</fullName>
                </value>
                <value>
                    <fullName>IG Draft Response</fullName>
                </value>
                <value>
                    <fullName>IG Final Response</fullName>
                </value>
                <value>
                    <fullName>Instructional Letter</fullName>
                </value>
                <value>
                    <fullName>Interagency Agreement</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Lease Prospectus</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>MOU</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health</fullName>
                </value>
                <value>
                    <fullName>OMB Scorecard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Stage_Start_Date_New__c</fullName>
        <label>Current Stage Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_On_Current_Stage_New__c</fullName>
        <label>Days On Current Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Program Review</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location_and_Stage_History__c.object
<CustomObject>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Office_Durations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location and Stage History</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location and Stage Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AutomatedStageUpdate.cls
public with sharing class AutomatedStageUpdate {

    private static ApprovalStepDAI appStepDA = new ApprovalStepDA();


    public static void updateControlledDocumentStage(Controlled_Document__c newControlledDocument, Approval_Step__c latestStep){
        String inboundStage = newControlledDocument.Stage__c;
        
        
        if(inboundStage != ControlledDocumentConstants.STAGE_HOLD || (inboundStage == ControlledDocumentConstants.STAGE_HOLD && latestStep.Approval_Status__c != 'Initiated/Closed')){
            String stage = getStageToUpdate(latestStep, newControlledDocument);
            newControlledDocument.Stage__c = stage;
        }
        
        if (inboundStage != newControlledDocument.Stage__c){
            newControlledDocument.Current_Stage_Start_Date_New__c = System.now().date();
            newControlledDocument.Days_On_Current_Stage_New__c = 0;
        }
    }

    public static void setMockDA(ApprovalStepDAMock dataAccessor){
        //use in test
        appStepDA = dataAccessor;
    }


    private static String getStageToUpdate(Approval_Step__c approvalStep, Controlled_Document__c document){
        String stageString = '';
        if(roleIsOfficePocOrDrafter(approvalStep.Role_of_Approver__c)){
            if (documentStageWasNotAutomatedAwayFromDrafting(approvalStep)){
                stageString = ControlledDocumentConstants.STAGE_DRAFTING;
            }else{
                stageString = ControlledDocumentConstants.STAGE_REVISE;
            }
        }else{
            if (docTypeIsDirectiveOrOrderOrInstructionalLetter(document.Correspondence_Type__c)){
                if (approvalStep.Role_of_Approver__c == ControlledDocumentConstants.EDITOR){
                    stageString = ControlledDocumentConstants.STAGE_CONCURRENCE;
                }else{
                    if(wasDocumentPreviouslyInReviseStage(document)){
                        stageString = ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE;
                    }else if (document.Stage__c == ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE) { //for ticket# RITM0636351 - BEGIN
                    	stageString = ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE;
                    } //for ticket# RITM0636351 - END
                    else{
                        stageString = ControlledDocumentConstants.STAGE_PROGRAM_REVIEW;
                    }
                }
            }else{
                if(roleIsApproverOrEditorOrReviewer(approvalStep.Role_of_Approver__c)){
                    stageString = ControlledDocumentConstants.STAGE_CONCURRENCE;
                }else{
                    System.debug('--- There is no stage for this approver role ---');
                    stageString = document.Stage__c;
                }
            }
        }
        return stageString;
    }


    private static Boolean roleIsOfficePocOrDrafter(String roleOfApprover){
        return (roleOfApprover == ControlledDocumentConstants.OFFICE_POC ||
                roleOfApprover == ControlledDocumentConstants.DRAFTER);
    }

    private static Boolean roleIsApproverOrEditorOrReviewer(String roleOfApprover){
        return (roleOfApprover == ControlledDocumentConstants.APPROVER ||
                roleOfApprover == ControlledDocumentConstants.APPROVER_SME ||
                roleOfApprover == ControlledDocumentConstants.EDITOR ||
                roleOfApprover == ControlledDocumentConstants.EXECSEC_REVIEWER);
    }

    private static Boolean docTypeIsDirectiveOrOrderOrInstructionalLetter(String docType){
        return (docType == ControlledDocumentConstants.TYPE_DIRECTIVE ||
                docType == ControlledDocumentConstants.TYPE_ORDER ||
                docType == ControlledDocumentConstants.TYPE_INSTRUCTIONAL_LETTER);
    }

    private static Boolean documentStageWasNotAutomatedAwayFromDrafting(Approval_Step__c approvalStep){
        List<Approval_Step__c> stepHistory = appStepDA.getAllInitiatedApprovalStepsWithControlledDocumentId(approvalStep.Correspondence_Document__c);
        for (Approval_Step__c step : stepHistory){
            if (!roleIsOfficePocOrDrafter(step.Role_of_Approver__c)){
                return false;
            }
        }
        return true;
    }

    private static Boolean wasDocumentPreviouslyInReviseStage(Controlled_Document__c document){
        //return document.Stage__c == ControlledDocumentConstants.STAGE_REVISE; // Commented for ticket # RITM0636351
        //for ticket# RITM0636351 - BEGIN
        if(document.Stage__c == ControlledDocumentConstants.STAGE_REVISE) {
            return true;
        } else {
            List<Location_and_Stage_History__c> reviseHistoryList = new List<Location_and_Stage_History__c>();
            reviseHistoryList = [SELECT Id, Stage__c, Controlled_Document__c FROM Location_and_Stage_History__c 
                                 WHERE Controlled_Document__c = :document.Id AND Stage__c = :ControlledDocumentConstants.STAGE_REVISE ];
            return ( (reviseHistoryList != null && !reviseHistoryList.isEmpty()) ? true : false);
        }    
        //for ticket# RITM0636351 - END
    }

}