src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Approver (SME)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <inlineHelpText>The type of document represented by the primary file(s) being approved through this record.</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Plan</fullName>
                </value>
                <value>
                    <fullName>AFR</fullName>
                </value>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>ASF: Cost &amp; Capital Plan</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Directive</fullName>
                </value>
                <value>
                    <fullName>E-Gov Reporting</fullName>
                </value>
                <value>
                    <fullName>FISMA</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>GAO Draft Response</fullName>
                </value>
                <value>
                    <fullName>GAO Final Response</fullName>
                </value>
                <value>
                    <fullName>Hazardous Waste Report</fullName>
                </value>
                <value>
                    <fullName>Home-To-Work</fullName>
                </value>
                <value>
                    <fullName>IG Audit</fullName>
                </value>
                <value>
                    <fullName>IG Draft Response</fullName>
                </value>
                <value>
                    <fullName>IG Final Response</fullName>
                </value>
                <value>
                    <fullName>Instructional Letter</fullName>
                </value>
                <value>
                    <fullName>Interagency Agreement</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Lease Prospectus</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>MOU</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health</fullName>
                </value>
                <value>
                    <fullName>OMB Scorecard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Program Review</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AutomatedStageUpdateTest.cls
@isTest
public with sharing class AutomatedStageUpdateTest {

	private static Integer fakePostfix = 1;

	@isTest
	public static void updateControlledDocumentStage_givenOfficePOC_shouldGiveStageDrafting(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC);
		mockDA.mockList.add(step);
		AutomatedStageUpdate.setMockDA(mockDA);

		Controlled_Document__c document = new Controlled_Document__c(Stage__c = ControlledDocumentConstants.STAGE_INITIATED);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_DRAFTING, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenDrafterAndNonDraftingStep_shouldGiveStageRevise(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.EXECSEC_REVIEWER);
		mockDA.mockList.add(step1);
		Approval_Step__c step2 = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.DRAFTER);
		mockDA.mockList.add(step2);

		AutomatedStageUpdate.setMockDA(mockDA);

		Controlled_Document__c document = new Controlled_Document__c(Stage__c = ControlledDocumentConstants.STAGE_INITIATED);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step2);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_REVISE, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenEditorAndInsLetter_shouldGiveStageConcurrence(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.EDITOR;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		document.Correspondence_Type__c = ControlledDocumentConstants.TYPE_INSTRUCTIONAL_LETTER;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_CONCURRENCE, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenApproverAndOrder_shouldGiveStageProgReview(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.APPROVER;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		document.Correspondence_Type__c = ControlledDocumentConstants.TYPE_ORDER;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_PROGRAM_REVIEW, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenApproverAndDirectiveAndRevise_shouldGiveStageDirClearance(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.APPROVER;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_REVISE;
		document.Correspondence_Type__c = ControlledDocumentConstants.TYPE_DIRECTIVE;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_REVISE, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenExecSecReviewer_shouldGiveStageDirConcurrence(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.EXECSEC_REVIEWER;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_CONCURRENCE, document.Stage__c);

	}

	@isTest
	public static void updateControlledDocumentStage_givenFYI_shouldRemainSameStage(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.FYI;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertEquals(ControlledDocumentConstants.STAGE_INITIATED, document.Stage__c);

	}
    //for ticket# RITM0636351 - BEGIN
    @isTest
	public static void updateControlledDocumentStage_givenApproverAndDirectiveAndRevise_shouldRetainStageDirClearance(){
		ApprovalStepDAMock mockDA = new ApprovalStepDAMock();

		Approval_Step__c step1 = new Approval_Step__c();
		step1.Role_of_Approver__c = ControlledDocumentConstants.APPROVER;

		Controlled_Document__c document = new Controlled_Document__c();
		document.Stage__c = ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE;
		document.Correspondence_Type__c = ControlledDocumentConstants.TYPE_DIRECTIVE;

		mockDA.mockList.add(step1);
		AutomatedStageUpdate.setMockDA(mockDA);

		Test.startTest();
		AutomatedStageUpdate.updateControlledDocumentStage(document, step1);
		Test.stopTest();

		System.assertNotEquals(ControlledDocumentConstants.STAGE_REVISE, document.Stage__c);
		System.assertEquals(ControlledDocumentConstants.STAGE_DIRECTIVES_CLEARANCE, document.Stage__c);

	}
	//for ticket# RITM0636351 - END
}