src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Approver__c</fullName>
        <label>Actual Approver</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Step_Type__c</fullName>
        <label>Approval Step Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual Approver</fullName>
                </value>
                <value>
                    <fullName>Group of Approvers - One Approval Needed</fullName>
                </value>
                <value>
                    <fullName>Group of Approvers - All Must Approve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_s_Division_Code__c</fullName>
        <description>The Division_Code indicated for the Controlled Document on which this Approval Step is listed.</description>
        <label>Approver&apos;s Division Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_s_Division_Name__c</fullName>
        <description>The Division Name indicated for the Controlled Document on which this Approval Step is listed.</description>
        <label>Approver&apos;s Division Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_s_Location__c</fullName>
        <description>The Approver&apos;s Location indicated for the Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>This field shows the office that is taking action on the record.</inlineHelpText>
        <label>Approver&apos;s Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_s_Organization_Acronym__c</fullName>
        <description>The Organization Acronym indicated for the Controlled Document on which this Approval Step is listed.</description>
        <label>Approver&apos;s Organization Acronym</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_s_Region_Location__c</fullName>
        <description>The Region indicated for the Controlled Document on which this Approval Step is listed.</description>
        <label>Approver&apos;s Region</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <description>The date the Approval Step was completed (i.e., a decision was made).</description>
        <inlineHelpText>The date the Approval Step was completed (i.e., a decision was made).</inlineHelpText>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <description>The number of business days that elapse after this Approval Step was initiated and before it was completed.</description>
        <inlineHelpText>The number of business days that elapse after this Approval Step was initiated and before it was completed.</inlineHelpText>
        <label>Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <label>Delegate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delegate</fullName>
                </value>
                <value>
                    <fullName>ExecSec</fullName>
                </value>
                <value>
                    <fullName>Approver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Due_Date__c</fullName>
        <description>The Due Date of the Controlled Document on which this Approval Step is listed.</description>
        <formula>Correspondence_Document__r.Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Due Date of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Stage__c</fullName>
        <description>The Stage of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Stage of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Title__c</fullName>
        <description>The Title of the Controlled Document on which this Approval Step is listed.</description>
        <formula>Correspondence_Document__r.Title_Formula__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Title of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exec_Sec_Proxy_Approval_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exec Sec Proxy Approval Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Review_Party__c</fullName>
        <description>When the &quot;Role of Approver&quot; is marked as &quot;External Review&quot;, this field indicates the external party that is conducting the review.</description>
        <inlineHelpText>When the &quot;Role of Approver&quot; is marked as &quot;External Review&quot;, this field indicates the external party that is conducting the review.</inlineHelpText>
        <label>External Review Party</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</description>
        <inlineHelpText>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</inlineHelpText>
        <label>Deactivate Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Note_about_Approve_w_Comments__c</fullName>
        <defaultValue>&quot;In order to mark this step with a status of Approved w Comments, you must first mark the step as Approved. On the following page, you will have the option to mark the step as Approved w Comments.&quot;</defaultValue>
        <description>This field is a read-only field that displays text for the user instructing them to first Approve an Approval Step before attempting to set the status to &quot;Approved w Comments&quot;</description>
        <label>Note:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApprovalStepDA.cls
public with sharing class ApprovalStepDA implements ApprovalStepDAI{
    public List<Approval_Step__c> getAllInitiatedApprovalStepsWithControlledDocumentId(Id docId){
        return[
                SELECT Id,
                    LastModifiedDate,
                    Actual_Approver__c,
                    Approval_Status__c,
                    Approval_Step_Type__c,
                    Assigned_Approver__c,
                    Approver_s_Division_Code__c,
                    Approver_s_Division_Name__c,
                    Approver_s_Location__c,
                    Approver_s_Organization_Acronym__c,
                    Approver_s_Region_Location__c,
                    Office__c,
                    Comments__c,
                    Completed_Date__c,
                    Correspondence_Document__c,
                    Days_Open__c,
                    Marked_for_Deletion__c,
                    Delegate__c,
                    Document_Due_Date__c,
                    Document_Stage__c,
                    Document_Title__c,
                    Correspondence_Type__c,
                    Due_Date__c,
                    Exec_Sec_Proxy_Approval_Requested__c,
                    External_Review_Party__c,
                    Note_about_Approve_w_Comments__c,
                    Notification_History_Trigger__c,
                    Office_Portfolio__c,
                    Originating_Service_Staff_Office__c,
                    Region__c,
                    Role_of_Approver__c,
                    Sequence__c,
                    Start_Date__c,
                    Time_Initiated__c
                FROM Approval_Step__c
                WHERE Correspondence_Document__c = :docId
                    AND Approval_Status__c != 'Not Initiated'
                ORDER BY Time_Initiated__c DESC NULLS LAST
        ];
    }

    public List<Approval_Step__c> getAllInitiatedApprovalStepsWithControlledDocumentIds(List<Id> docIds){
        return[
                SELECT Id,
                        LastModifiedDate,
                        Actual_Approver__c,
                        Approval_Status__c,
                        Approval_Step_Type__c,
                        Assigned_Approver__c,
                        Approver_s_Division_Code__c,
                        Approver_s_Division_Name__c,
                        Approver_s_Location__c,
                        Approver_s_Organization_Acronym__c,
                        Approver_s_Region_Location__c,
                        Office__c,
                        Comments__c,
                        Completed_Date__c,
                        Correspondence_Document__c,
                        Days_Open__c,
                        Marked_for_Deletion__c,
                        Delegate__c,
                        Document_Due_Date__c,
                        Document_Stage__c,
                        Document_Title__c,
                        Correspondence_Type__c,
                        Due_Date__c,
                        Exec_Sec_Proxy_Approval_Requested__c,
                        External_Review_Party__c,
                        Note_about_Approve_w_Comments__c,
                        Notification_History_Trigger__c,
                        Office_Portfolio__c,
                        Originating_Service_Staff_Office__c,
                        Region__c,
                        Role_of_Approver__c,
                        Sequence__c,
                        Start_Date__c,
                        Time_Initiated__c
                FROM Approval_Step__c
                WHERE Correspondence_Document__c IN :docIds
                AND Approval_Status__c != 'Not Initiated'
                AND Approval_Status__c != 'Initiated/Closed'
                ORDER BY Time_Initiated__c DESC NULLS LAST
        ];
    }

    public List<AggregateResult> getMaxInitiatedTimeForDocumentIds(List<Id> docIds){
        return [SELECT Correspondence_Document__c,
                MAX(Time_Initiated__c)maxInitTime
        FROM Approval_Step__c
        WHERE Correspondence_Document__c IN :docIds
        GROUP BY Correspondence_Document__c];
    }

}