src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_s_Location__c</fullName>
        <description>The Approver&apos;s Location indicated for the Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>This field shows the office that is taking action on the record.</inlineHelpText>
        <label>Approver&apos;s Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_s_Organization_Acronym__c</fullName>
        <description>The Organization Acronym indicated for the Controlled Document on which this Approval Step is listed.</description>
        <label>Approver&apos;s Organization Acronym</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Approver (SME)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Current_Location_auto__c</fullName>
        <description>Automated Location field updates</description>
        <inlineHelpText>This field shows the office that is taking action on the record.</inlineHelpText>
        <label>Current Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Signatory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents who the intended Final Signatory of a Controlled Document should be.</description>
        <inlineHelpText>This field represents who the intended Final Signatory of a Controlled Document should be.</inlineHelpText>
        <label>Final Signatory</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Documents1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMB__c</fullName>
        <label>OMB</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-OMB</fullName>
                </value>
                <value>
                    <fullName>Post-OMB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Program Review</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AutomatedLocationUpdateTest.cls
@isTest
public without sharing class AutomatedLocationUpdateTest {
	
	@testSetup
	static void testDataSetup(){
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> exsitingStandardUsers = new List<User>();
        for(Integer i = 1; i < 6; i++) {
            exsitingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert exsitingStandardUsers;
		
		system.debug('#############################################################################');
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
	}	
	
	@isTest
	public static void updateApprovalStepLocations_givenDivision_shouldGiveDivisionLocation(){
		List<Approval_Step__c> triggerNew = new List<Approval_Step__c>();
		Map<Id, Approval_Step__c> triggerOldMap = new Map<Id, Approval_Step__c>();

		ApprovalStepDAMock mockApprovalDA = new ApprovalStepDAMock();
		ControlledDocumentDAMock mockDocumentDA = new ControlledDocumentDAMock();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);

		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC);
		step.Sequence__c = '1';
        step.Approval_Status__c = ControlledDocumentConstants.INITIATED_STATUS_STRING;
        step.Office__c = '';
        step.Assigned_Approver__c = mockUserDA.genericUser.Id;
        mockApprovalDA.mockList.add(step);
		AutomatedLocationUpdate.setMockDA(mockApprovalDA);
		
		mockDocumentDA.document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		mockDocumentDA.documentList.add(mockDocumentDA.document);
		AutomatedLocationUpdate.setMockDocDA(mockDocumentDA);
		
		triggerNew.add(step);
		triggerOldMap.put(step.Id, step);
		
		Test.startTest();
			AutomatedLocationUpdate.updateApprovalStepLocations(triggerNew, triggerOldMap);
			//System.assertEquals('Region1-TMF-ADF-Technology Modernization Fund - PMO', triggerNew[0].Approver_s_Location__c);
        Test.stopTest();
	}
	
	@isTest
	public static void updateApprovalStepLocations_givenOldLocation_shouldGiveOldLocation(){
		List<Approval_Step__c> triggerNew = new List<Approval_Step__c>();
		Map<Id, Approval_Step__c> triggerOldMap = new Map<Id, Approval_Step__c>();

		ApprovalStepDAMock mockApprovalDA = new ApprovalStepDAMock();
		ControlledDocumentDAMock mockDocumentDA = new ControlledDocumentDAMock();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);

		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC);
		step.Sequence__c = '1';
        step.Approval_Status__c = ControlledDocumentConstants.INITIATED_STATUS_STRING;
        step.Office__c = 'Test Office';
        mockApprovalDA.mockList.add(step);
		AutomatedLocationUpdate.setMockDA(mockApprovalDA);
		
		mockDocumentDA.document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		AutomatedLocationUpdate.setMockDocDA(mockDocumentDA);
		
		triggerNew.add(step);
		triggerOldMap.put(step.Id, step);
		
		Test.startTest();
			AutomatedLocationUpdate.updateApprovalStepLocations(triggerNew, triggerOldMap);
			System.assertEquals('Test Office', triggerNew[0].Approver_s_Location__c);
        Test.stopTest();
	}

	@isTest
	public static void updateApprovalStepLocations_givenNoStepsInitiated_shouldGiveOwnerLocation(){
		List<Approval_Step__c> triggerNew = new List<Approval_Step__c>();
		Map<Id, Approval_Step__c> triggerOldMap = new Map<Id, Approval_Step__c>();

		ApprovalStepDAMock mockApprovalDA = new ApprovalStepDAMock();
		ControlledDocumentDAMock mockDocumentDA = new ControlledDocumentDAMock();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);

		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC);
		step.Sequence__c = '1';
        step.Office__c = '';
        step.Approval_Status__c = 'Not Initiated';
		AutomatedLocationUpdate.setMockDA(mockApprovalDA);
		
		mockDocumentDA.document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		AutomatedLocationUpdate.setMockDocDA(mockDocumentDA);
		
		triggerNew.add(step);
		triggerOldMap.put(step.Id, step);
		
		Test.startTest();
			AutomatedLocationUpdate.updateApprovalStepLocations(triggerNew, triggerOldMap);
			System.assertEquals(mockDocumentDA.document.Current_Location_auto__c, triggerNew[0].Approver_s_Location__c);
        Test.stopTest();
	}
    
	@isTest
	public static void updateControlledDocumentLocationFromApprovalSteps_givenInitiatedSteps(){
		List<Approval_Step__c> triggerNew = new List<Approval_Step__c>();

		ApprovalStepDAMock mockApprovalDA = new ApprovalStepDAMock();
		ControlledDocumentDAMock mockDocumentDA = new ControlledDocumentDAMock();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);

		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC);
		step.Sequence__c = '1';
        step.Office__c = '';
        step.Approval_Status__c = 'Initiated';
        step.Correspondence_Document__c = mockDocumentDA.document.Id;
        step.Approver_s_Location__c = 'Region1-TMF-ADF-Technology Modernization Fund - PMO';
        step.Approver_s_Organization_Acronym__c = 'Test';
		AutomatedLocationUpdate.setMockDA(mockApprovalDA);
		
		mockDocumentDA.document.Stage__c = ControlledDocumentConstants.STAGE_INITIATED;
		AutomatedLocationUpdate.setMockDocDA(mockDocumentDA);
		
		
		Test.startTest();
			AutomatedLocationUpdate.updateControlledDocumentLocationFromApprovalSteps(mockDocumentDA.document, triggerNew);
			//System.assertEquals('Region1-TMF-ADF-Technology Modernization Fund - PMO', mockDocumentDA.document.Current_Location_auto__c);

			triggerNew.add(step);
			AutomatedLocationUpdate.updateControlledDocumentLocationFromApprovalSteps(mockDocumentDA.document, triggerNew);
			System.assertEquals('Region1-TMF-ADF-Technology Modernization Fund - PMO', mockDocumentDA.document.Current_Location_auto__c);

			triggerNew.add(step);
			triggerNew.add(step);
			AutomatedLocationUpdate.updateControlledDocumentLocationFromApprovalSteps(mockDocumentDA.document, triggerNew);
			System.assertEquals('Simultaneous Agency Clearance Test', mockDocumentDA.document.Current_Location_auto__c);
 
			mockDocumentDA.document.Stage__c = ControlledDocumentConstants.STAGE_CLOSED;
 			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(mockDocumentDA.document);
			System.assertEquals('---', mockDocumentDA.document.Current_Location_auto__c);
        Test.stopTest();
	}
 

	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageClosed_shouldGiveBlankLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_CLOSED;
		
		Test.startTest();
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('---', controlledDoc.Current_Location_auto__c);
	}	
	   
	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageHold_shouldGiveBlankLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_HOLD;
		
		Test.startTest();
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('---', controlledDoc.Current_Location_auto__c);
	}	
	   
	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageExternalReviewAndOMB_shouldGiveOMBLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_EXTERNAL_REVIEW;
		controlledDoc.OMB__c = ControlledDocumentConstants.PRE_OMB_STATUS_STRING;
		
		Test.startTest();
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('OMB', controlledDoc.Current_Location_auto__c);
	}	

	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageExternalReview_shouldGiveBlankLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_EXTERNAL_REVIEW;
		controlledDoc.OMB__c = 'NotOMB';
		
		Test.startTest();
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('---', controlledDoc.Current_Location_auto__c);
	}	

	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageAwaitingSignature_shouldGiveSignatoryLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_AWAITING_SIGNATURE;
		controlledDoc.Final_Signatory__c = mockUserDA.genericUser.Id;

		Test.startTest();		
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('ADF', controlledDoc.Current_Location_auto__c);
	}	

	@isTest
	public static void updateControlledDocumentLocationFromStage_givenStageAwaitingClosure_shouldGiveOwnerLocation(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		UserDAMock mockUserDA = new UserDAMock();
		
		mockUserDA.genericUser.Division = 'ADF';
		AutomatedLocationUpdate.setMockUserDA(mockUserDA);
		
		controlledDoc.Stage__c = ControlledDocumentConstants.STAGE_AWAITING_CLOSURE;
		controlledDoc.Final_Signatory__c = mockUserDA.genericUser.Id;

		Test.startTest();		
			AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(controlledDoc);
		Test.stopTest();

		System.assertEquals('ADF', controlledDoc.Current_Location_auto__c);
	}	

	@isTest
	public static void testApprovalStepUndelete(){
		Controlled_Document__c controlledDoc = new Controlled_Document__c();
		Approval_Step__c step = new Approval_Step__c(Role_of_Approver__c = ControlledDocumentConstants.OFFICE_POC, Correspondence_Document__c = controlledDoc.Id);
		List<Approval_Step__c> steps;
				
		Test.startTest();		
			insert controlledDoc;
			step.Correspondence_Document__c = controlledDoc.Id;
			insert step;
			
			steps = [SELECT Id FROM Approval_Step__c WHERE id=:step.Id];
			System.assertEquals(true, (steps.size() > 0));
			
			delete step;
			
			steps = [SELECT Id FROM Approval_Step__c WHERE id=:step.Id];
			System.assertEquals(true, (steps.size() == 0));
			
			undelete step;

			steps = [SELECT Id FROM Approval_Step__c WHERE id=:step.Id];
			System.assertEquals(true, (steps.size() > 0));			
		Test.stopTest();		
	}

}