src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApprovalStepSelect.cls
 public with sharing class ApprovalStepSelect {
	public Approval_Step__c approvalStep {get; set;}
	public Boolean selected {get; set;}

	public ApprovalStepSelect(Approval_Step__c approvalStep) {
		this.approvalStep = approvalStep;
		selected = false;
	}

	public ApprovalStepSelect(ApprovalStepSelect step){
		this.approvalStep = step.approvalStep.clone(true, true);
		this.selected = step.selected;
	}

	public Boolean getIsLocked(){
		return approvalStep.Approval_Status__c == ControlledDocumentConstants.INITIATED_STATUS_STRING ||
			   approvalStep.Approval_Status__c == ControlledDocumentConstants.REJECTED_STATUS_STRING ||
		       approvalStep.Approval_Status__c == ControlledDocumentConstants.APPROVED_STATUS_STRING ||
		       approvalStep.Approval_Status__c == ControlledDocumentConstants.APPROVED_WITH_COMMENTS_STATUS_STRING;
	}
}