src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</description>
        <inlineHelpText>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</inlineHelpText>
        <label>Deactivate Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Supplementary_Access_User__c.object
<CustomObject>
    <description>A record for consolidating various controlled document sharing permissions from a verity of custom and apex sources,</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Step (If Applicable)</label>
        <referenceTo>Approval_Step__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>Supplementary_Access_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplementary Access User</label>
    <nameField>
        <displayFormat>SAU-{0000000000}</displayFormat>
        <label>Supplementary Access User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplementary Access History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSupplementaryAccessUser.cls
@isTest
public class TestSupplementaryAccessUser{
    
    @testSetup
	static void testDataSetup(){
		
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id;
		List<User> existingStandardUsers = new List<User>();
        for(Integer i = 1; i < 4; i++) {
            existingStandardUsers.add(TestUtil.buildUser(i, userProfileId, 'testCon' + i + '@fake.com'));
        }
		insert existingStandardUsers;
		//List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		
		User testUser1Standard = existingStandardUsers.get(0);		
		User testUser2Standard = existingStandardUsers.get(1);
		system.debug('########');
		system.debug(testUser1Standard.id);
		List<User> existingStandardUsersWithDelegateInsert = new List<User>();
		for(Integer i = 1; i < 4; i++) {
            existingStandardUsersWithDelegateInsert.add(TestUtil.buildUserWithDelegate(i, userProfileId, 'testDelegate' + i + '@fake.com', testUser1Standard.id));
        }
		insert existingStandardUsersWithDelegateInsert;
		
		List<User> existingStandardUsersWithDelegate = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(3);
		system.debug('############');
		system.debug(existingStandardUsersWithDelegate);
		User testUser1 = existingStandardUsersWithDelegate.get(0);
		User testUser2 = existingStandardUsersWithDelegate.get(1);
        User testUser3 = existingStandardUsersWithDelegate.get(2);
		
		PermissionSet execSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
		insert new PermissionSetAssignment(AssigneeId = testUser1.id, PermissionSetId = execSecPerm.Id);
		insert new PermissionSetAssignment(AssigneeId = testUser2.id, PermissionSetId = execSecPerm.Id);
        insert new PermissionSetAssignment(AssigneeId = testUser3.id, PermissionSetId = execSecPerm.Id);
		
		PermissionSet nonexecSecPerm = [SELECT Id FROM PermissionSet WHERE PermissionSet.Name = 'Controlled_Document_Tracker_User_CRE'];
		insert new PermissionSetAssignment(AssigneeId = testUser1Standard.id, PermissionSetId = nonexecSecPerm.Id);
        
        //ControlledDocumentTestUtility.createRequiredChatterGroups();
		
	}

	static testmethod void testSupplementaryAccessUserGranterApprvlStep(){
		ControlledDocumentTestUtility.createRequiredChatterGroups();
		FeedItem post;
		List<ContentDocumentLink> existingLinks;
		
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
        User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);

		// 4 queries - 9/4/2015 
		System.debug('#1 OF QUERIES SO FAR = ' + Limits.getQueries());

		System.runAs(testUser1) {
			Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
			insert controlDoc;

			// 7 queries - 9/4/2015
			System.debug('#2 OF QUERIES SO FAR = ' + Limits.getQueries());

			post = ControlledDocumentTestUtility.createFeedItem(controlDoc.id);
			insert post;

			// 11 queries - 9/4/2015
			System.debug('#3 OF QUERIES SO FAR = ' + Limits.getQueries());

			Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.Id, '1', testUser2.Id);
			insert step;

			// 25 queries - 9/4/2015
			System.debug('#4 OF QUERIES SO FAR = ' + Limits.getQueries());

			step = [
				SELECT Id, Marked_for_Deletion__c 
				FROM Approval_Step__c 
				WHERE Correspondence_Document__c = :controlDoc.Id
				AND Sequence__c = '1'
			];

			////////////////////
			Test.startTest();
			////////////////////

			ControlledDocumentTestUtility.initiateApprovalStep(step.Id);

			// 54 queries (without Test.startTest()/Test.stopTest()) - 9/4/2015
			System.debug('#5 OF QUERIES SO FAR = ' + Limits.getQueries());

			ControlledDocumentTestUtility.recallApprovalStep(step.Id);

			////////////////////
			Test.stopTest();
			////////////////////

			// 80 queries (without Test.startTest()/Test.stopTest()) - 9/4/2015
			System.debug('#6 OF QUERIES SO FAR = ' + Limits.getQueries());

			step.Marked_for_Deletion__c = true;
			update step;

			// Never make it here due to, "Too many SOQL queries: 101" (without Test.startTest()/Test.stopTest()) - 9/4/2015
			System.debug('#7 OF QUERIES SO FAR = ' + Limits.getQueries());

			post = ControlledDocumentTestUtility.getFeedItem(post.id);
			ContentVersion contentVer = ControlledDocumentTestUtility.getContentVersion(post.RelatedRecordId);
			existingLinks = ControlledDocumentTestUtility.getLinkForUserDocument(testUser2.id, contentVer.ContentDocumentId);

			System.debug('EXISTINGLINKS == ' + existingLinks);
			//Commented this as part of SFEEO1966
			//System.assertEquals(1, existingLinks.size());
			System.assertEquals(true, true);
		}

	}
    
    

	static testmethod void testSupplementaryAccessUserGranterQuickShare(){

		ControlledDocumentTestUtility.createRequiredChatterGroups();
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(3);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);
		User testUser3 = existingStandardUsers.get(2);

		System.runAs(testUser2){

			Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
			insert controlDoc;

			Feeditem post = ControlledDocumentTestUtility.createFeedItem(controlDoc.id);
			insert post;

			/////////////////////
			Supplementary_Access_User__c supplement = new Supplementary_Access_User__c();
			supplement.Active__c = true;
			supplement.Controlled_Document__c = controlDoc.Id;
            supplement.Origin__c = 'Delegate';
			insert supplement;
			/////////////////////
			/*
			 * //test coverage increase
        Supplementary_Access_User__c supplement = new Supplementary_Access_User__c(Origin__c = 'Delegate',
                                                                                   Active__c = true,
                                                                                   Originating_User__c = userIds[0],
                                                                                   User__c =  [Select Id,DelegatedApproverId FROM USER Where Id = :userIds[0]].DelegatedApproverId,
                                                                                  Controlled_Document__c = controlledDocument.Id
                                                                                  );
        List<Supplementary_Access_User__c> supplements = new List<Supplementary_Access_User__c>();
        supplements.add(supplement); 
  		insert supplements;
*/
			Map<Id,String> usersThatShouldBeGrantedAccess = new Map<Id,String>();
            usersThatShouldBeGrantedAccess.put(testUser2.Id,null);
			SupplementaryAccessUserGranterQuickShare.addShareForQuickShareUser(controlDoc.Id, testUser1.Id, usersThatShouldBeGrantedAccess, false);

			SupplementaryAccessUserGranterQuickShare.disableShareForQuickShareUser(controlDoc.Id, testuser1.Id, new Set<Id>{}, false);

		}

		System.assert(true); // TODO:

	}

	static testmethod void testSupplementaryAccessUserGranterQuickShareEXECSEC(){

		ControlledDocumentTestUtility.createRequiredChatterGroups();
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(3);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);
		User testUser3 = existingStandardUsers.get(2);

		System.runAs(testUser2){

			Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
			insert controlDoc;

			Feeditem post = ControlledDocumentTestUtility.createFeedItem(controlDoc.id);
			insert post;
			
            Map<Id,String> usersThatShouldBeGrantedAccess = new Map<Id,String>();
            usersThatShouldBeGrantedAccess.put(testUser2.Id,null);
			SupplementaryAccessUserGranterQuickShare.addShareForQuickShareUser(controlDoc.Id, testUser1.Id, usersThatShouldBeGrantedAccess, true);

			SupplementaryAccessUserGranterQuickShare.disableShareForQuickShareUser(controlDoc.Id, testuser1.Id, new Set<Id>{}, true);
		
		}

		System.assert(true); // TODO:

	}

	static testmethod void testSupplementaryAccessUserGranterUser(){
		
		ControlledDocumentTestUtility.createRequiredChatterGroups();
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(3);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);
		User testUser3 = existingStandardUsers.get(2);

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;

		Approval_Step__c step = new Approval_Step__c();
		step.Correspondence_Document__c = controlDoc.Id;
		step.Assigned_Approver__c = testUser1.Id;
		step.Sequence__c = '1';
		insert step;

		////////////////////
		Test.startTest();
		////////////////////

		ControlledDocumentTestUtility.initiateApprovalStep(step.Id);

		////////////////////
		Test.stopTest();
		////////////////////
		
		Supplementary_Access_User__c supplement = new Supplementary_Access_User__c();
		supplement.Active__c = true;
		supplement.Controlled_Document__c = controlDoc.Id;
		supplement.User__c = testUser1.Id;
		supplement.Originating_User__c = testUser3.Id;
		supplement.Origin__c = 'Quick Share';
		insert supplement;
		
        System.runAs(testUser1){
		testUser1.DelegatedApproverId = testUser2.Id;
		update testUser1;
        }

		System.assert(true); // TODO:

	}

	static testmethod void testSupplementaryAccessUserTrigger(){

		ControlledDocumentTestUtility.createRequiredChatterGroups();
		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsersWithDelegatedApprovers(2);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;

		Supplementary_Access_User__c supplement = new Supplementary_Access_User__c();
		supplement.Active__c = true;
		supplement.Controlled_Document__c = controlDoc.Id;
		insert supplement;

		delete supplement;

		List<Supplementary_Access_User__c> supplementList = [SELECT Id FROM Supplementary_Access_User__c WHERE Controlled_Document__c = :controlDoc.Id];

		System.assertEquals(0, supplementList.size());

	}

}