src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the ExecSec user assigned to the record.</inlineHelpText>
        <label>ExecSec Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Division_Code__c</fullName>
        <label>Current Division Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Division_Name__c</fullName>
        <description>Automated Location field updates</description>
        <label>Current Division Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Location_Start_Date_New__c</fullName>
        <label>Current Location Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Location__c</fullName>
        <description>User selects what office/region/sub-office currently has the document</description>
        <label>Old Current Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
                <value>
                    <fullName>Region 4Q</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Location_auto__c</fullName>
        <description>Automated Location field updates</description>
        <inlineHelpText>This field shows the office that is taking action on the record.</inlineHelpText>
        <label>Current Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Organization_Acronym__c</fullName>
        <description>Automated Location field updates</description>
        <label>Current Organization Acronym</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Region__c</fullName>
        <label>Current Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Office</fullName>
                </value>
                <value>
                    <fullName>Region 1</fullName>
                </value>
                <value>
                    <fullName>Region 2</fullName>
                </value>
                <value>
                    <fullName>Region 3</fullName>
                </value>
                <value>
                    <fullName>Region 4</fullName>
                </value>
                <value>
                    <fullName>Region 5</fullName>
                </value>
                <value>
                    <fullName>Region 6</fullName>
                </value>
                <value>
                    <fullName>Region 7</fullName>
                </value>
                <value>
                    <fullName>Region 8</fullName>
                </value>
                <value>
                    <fullName>Region 9</fullName>
                </value>
                <value>
                    <fullName>Region 10</fullName>
                </value>
                <value>
                    <fullName>National Capital Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Region_auto__c</fullName>
        <description>Automated Location field updates</description>
        <label>Current Region</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Stage_Start_Date_New__c</fullName>
        <label>Current Stage Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_In_Current_Location_New__c</fullName>
        <label>Days In Current Location</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_On_Current_Stage_New__c</fullName>
        <label>Days On Current Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OMB__c</fullName>
        <label>OMB</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-OMB</fullName>
                </value>
                <value>
                    <fullName>Post-OMB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>The region (or Central Office) involved in originating or overseeing this Controlled Document record.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Office</fullName>
                </value>
                <value>
                    <fullName>Region 1</fullName>
                </value>
                <value>
                    <fullName>Region 2</fullName>
                </value>
                <value>
                    <fullName>Region 3</fullName>
                </value>
                <value>
                    <fullName>Region 4</fullName>
                </value>
                <value>
                    <fullName>Region 5</fullName>
                </value>
                <value>
                    <fullName>Region 6</fullName>
                </value>
                <value>
                    <fullName>Region 7</fullName>
                </value>
                <value>
                    <fullName>Region 8</fullName>
                </value>
                <value>
                    <fullName>Region 9</fullName>
                </value>
                <value>
                    <fullName>Region 10</fullName>
                </value>
                <value>
                    <fullName>National Capital Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Program Review</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location_and_Stage_History__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Office_Durations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>The Division Code indicated for the Controlled Document on which this record is related to.</description>
        <label>Division Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>The Division Name indicated for the Controlled Document on which this record is related to.</description>
        <label>Division Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Organization_Acronym__c</fullName>
        <description>The Organization Acronym indicated for the Controlled Document on which this record is related to.</description>
        <label>Organization Acronym</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>The Region indicated for the Controlled Document on which this record is related to.</description>
        <label>Region</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>of_Days_New__c</fullName>
        <label># of Days</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Location and Stage History</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location and Stage Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mapping_Object__c.object
<CustomObject>
    <fields>
        <fullName>Office_Portfolio__c</fullName>
        <label>Division Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Staff_Office__c</fullName>
        <label>Organization Acronym</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Object</label>
    <nameField>
        <label>Division Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Alternate_Division__c</fullName>
        <label>Alternate Division</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Region__c</fullName>
        <label>Alternate Region</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>Region</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/LocationAndStageHistoryHelper.cls
public class LocationAndStageHistoryHelper{

    private static ApprovalStepDAI appStepDA = new ApprovalStepDA();
    private static UserDAI userDA = new UserDA();
    private static ControlledDocumentDAI controlledDocDA = new ControlledDocumentDA();
    
    public static void setMockDA(ApprovalStepDAMock dataAccessor){
        //use in test
        appStepDA = dataAccessor;
    }
    public static void setMockUserDA(UserDAMock dataAccessor){
        //use in test
        userDA = dataAccessor;
    }
    public static void setMockDocDA(ControlledDocumentDAMock dataAccessor){
        //use in test
        controlledDocDA = dataAccessor;
    }


    // prevents adding a second location and stage history when the stage is changed to closed
    public static Map<Id, boolean> controlledDocumentIdRecursionTracker = new Map<Id, boolean>();
    public static BusinessHours cdtBusinessHours = [SELECT Id 
                                                FROM BusinessHours 
                                                WHERE Name = 'CDT Business Hours'];

    private static Boolean updatedFromApprovalStep = false;

    // BEFORE INSERT ONLY
    // inserts start dates and also sets the Current Location
    public static void insertStartDatesAndSetCurrentLocation(List<Controlled_Document__c> newCDocs){
        Date currentLocalDate = System.now().date();
        AutomatedLocationUpdate.locationValues locationVals = new AutomatedLocationUpdate.locationValues();
                
        for(Controlled_Document__c newControlledDocument : newCDocs){
            newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;
            newControlledDocument.Days_On_Current_Stage_New__c = 0;
            newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
            newControlledDocument.Days_In_Current_Location_New__c = 0;
            
            if (newControlledDocument.Stage__c != 'Awaiting Closure' && newControlledDocument.Stage__c != 'Awaiting Signature' && newControlledDocument.Stage__c != 'Hold' &&
                newControlledDocument.Stage__c != 'Closed' && newControlledDocument.Stage__c != 'External Review') {

                if (!String.isBlank(newControlledDocument.Assignee__c)) {
                    locationVals.updateWithUserId(newControlledDocument.Assignee__c, newControlledDocument.Id, newControlledDocument.Name);
                } else {
                    locationVals.updateWithUserId(newControlledDocument.OwnerId, newControlledDocument.Id, newControlledDocument.Name);
                }
                        
                newControlledDocument.Current_Region_Auto__c = locationVals.region;
                newControlledDocument.Current_Organization_Acronym__c = locationVals.orgAcronym;
                newControlledDocument.Current_Division_Code__c = locationVals.divisionCode; 
                newControlledDocument.Current_Division_Name__c = locationVals.divisionName; 
                newControlledDocument.Current_Location_auto__c = locationVals.concatenatedLocation; 
            }else{
                AutomatedLocationUpdate.updateControlledDocumentLocationFromStage(newControlledDocument);
            }
            
            
        }
    }


    public static void checkForNewDivision(List<Controlled_Document__c> newCDocs) {
        User tmpUser;
        Mapping_Object__c[] tmpMap;
        String tmpDivision;
            
        for(Controlled_Document__c newControlledDocument : newCDocs){
            tmpUser = [SELECT Id, Division, Alternate_Division__c, User_Region__c, Alternate_Region__c From User where Id =: newControlledDocument.OwnerId];
            tmpDivision = (String.isBlank(tmpUser.Division) ? tmpUser.Alternate_Division__c : tmpUser.Division);
        
            if (tmpDivision != null){
                tmpDivision = tmpDivision.left(3);                
            }
            
            tmpMap = [SELECT Id, Service_Staff_Office__c, Office_Portfolio__c FROM Mapping_Object__c WHERE Name =: tmpDivision];
    
            if (tmpMap.isEmpty()) {
                    
                Messaging.reserveSingleEmailCapacity(2);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    
                List<PermissionSetAssignment> execSecGroup = [SELECT AssigneeId, Assignee.Name, Assignee.Email FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
                String[] emailAddresses = new String[]{};
                for(PermissionSetAssignment assignment : execSecGroup) {
                    emailAddresses.add(assignment.Assignee.Email);
                }

                String[] ccAddresses = new String[] {};
                String recordLink = URL.getSalesforceBaseUrl().toExternalForm()+'/'+ newControlledDocument.Id;  
                
                mail.setToAddresses(emailAddresses);
                mail.setCcAddresses(ccAddresses);
                    
                //mail.setOrgWideEmailAddressId('0D230000000TPnh');//donotreply@gsa.gov
                mail.setSubject('New Division Location Added to CDT ' + newControlledDocument.Name);
                mail.setBccSender(false);
                mail.setUseSignature(false);
                
                mail.setPlainTextBody(
                    'A new division location was added to the following Controlled Document Tracker record: \n' +
                    'Record Number:' + newControlledDocument.Name + '\n' +
                    'Division: '+ tmpDivision + '\n\n' +
                    'Please update the following as needed:\n' +
                    '1) The record\'s Approval Steps section\n' +
                    '2) The record\'s Location and Stage Histories section (if the Approval Step has already been marked)\n' +
                    '3) The central list of user divisions'
                );
                    
                mail.setHtmlBody(
                    '<p>A new division location was added to the following Controlled Document Tracker record:</p>' +
                    '<p><strong>Record Number:</strong> <a href=\'' + recordLink + '\'>' + newControlledDocument.Name + '</a> <br/> <strong>Division:</strong> ' + tmpDivision + '</p>' +
                    '<p>Please update the following as needed:</p>' +
                    '<p>1) The record\'s Approval Steps section <br/>' +
                    '2) The record\'s Location and Stage Histories section (if the Approval Step has already been marked) <br/>' +
                    '3) The central list of user divisions</p>'
                );
                    
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                            
            }
        }
    }
    

    // AFTER INSERT ONLY
    public static void insertLocationHistoryForNewCDocs(List<Controlled_Document__c> newCDocs){
        Datetime current = System.now();
        Date currDate = current.date();
        Time currTime = current.time();
        Datetime currentLocal = Datetime.newInstance(currDate, currTime);

        List<Location_and_Stage_History__c> historiesToAdd = new List<Location_and_Stage_History__c>();
        for(Controlled_Document__c controlledDocument : newCDocs){            
            // if a CD is inserted as closed then this happens
            if(controlledDocument.Stage__c == 'Closed') continue;
            
            Location_and_Stage_History__c newHistoryLocation = new Location_and_Stage_History__c();
            
            // Case# 30668 - BEGIN
            //String locationName = (controlledDocument.current_Region__c != null) ? mergeString(controlledDocument.current_Region__c, 
            //                                                                                 controlledDocument.Current_Location__c) : null;
            //newHistoryLocation.Name = (locationName != null) ? locationName : controlledDocument.Current_Location__c;
            // Case# 30668 - END
            
            newHistoryLocation.Stage__c = controlledDocument.Stage__c;
            newHistoryLocation.Active__c = TRUE;
            newHistoryLocation.Start_Date__c = currentLocal;
            newHistoryLocation.of_Days_New__c = 0.0;
            newHistoryLocation.Controlled_Document__c = controlledDocument.Id;

            if (controlledDocument.Stage__c == 'Closed'){
                newHistoryLocation.End_Date__c = currentLocal;              
            }

            newHistoryLocation.Name = String.isNotBlank(controlledDocument.Current_Location_auto__c) ? controlledDocument.Current_Location_auto__c : '';
            newHistoryLocation.Region__c = String.isNotBlank(controlledDocument.Current_Region_Auto__c) ? ControlledDocument.Current_Region_Auto__c : '';   
            newHistoryLocation.Organization_Acronym__c = String.isNotBlank(controlledDocument.Current_Organization_Acronym__c) ? ControlledDocument.Current_Organization_Acronym__c : '';    
            newHistoryLocation.Division_Code__c = String.isNotBlank(controlledDocument.Current_Division_Code__c) ? ControlledDocument.Current_Division_Code__c : '';  
            newHistoryLocation.Division_Name__c = String.isNotBlank(controlledDocument.Current_Division_Name__c) ? ControlledDocument.Current_Division_Name__c : '';                  

            historiesToAdd.add(newHistoryLocation);
        }
        insert historiesToAdd;
    }

    // BEFORE UPDATE ONLY
    public static void checkAndUpdateHistory(Map<Id, Controlled_Document__c> newCDocs, Map<Id, Controlled_Document__c> oldCDocs){
        Datetime current = System.now();
        Date currDate = current.date();
        Time currTime = current.time();
        Time midnightTime = Time.newInstance(0, 0, 0, 0);
        Datetime currentLocal = Datetime.newInstance(currDate, currTime);
        Datetime currentLocalMidnight = Datetime.newInstance(currDate, midnightTime);
        Date currentLocalDate = currDate;

        List<Controlled_Document__c> cDocsNeedingHistoryChanges = new List<Controlled_Document__c>();
        for(Controlled_Document__c newControlledDocument : newCDocs.values()){
            // prevents closed controlled documents from running twice
            if(controlledDocumentIdRecursionTracker.get(newControlledDocument.Id) == true) {
                // allows another attempt after an initial 'closed' status in case a document is ever updated to 'closed' then to a new status in the same transcation
                // this should never happen -_-
                controlledDocumentIdRecursionTracker.put(newControlledDocument.Id, false);
                continue;
            }

            if(newControlledDocument.Stage__c == 'Closed'){
                newControlledDocument.Current_Location_Start_Date_New__c = null;
                newControlledDocument.Current_Stage_Start_Date_New__c = null;
                newControlledDocument.Days_In_Current_Location_New__c = null;
                newControlledDocument.Days_On_Current_Stage_New__c = null;
                cDocsNeedingHistoryChanges.add(newControlledDocument);
                continue;   
            }

            // this will help preventing nulls on existing controlled documents
            if(newControlledDocument.Current_Location_Start_Date_New__c == null) newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
            if(newControlledDocument.Current_Stage_Start_Date_New__c == null) newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;

            // used to prevent adding the same object to our list
            boolean added = false;
            if(newControlledDocument.Current_Location_auto__c != oldCDocs.get(newControlledDocument.Id).Current_Location_auto__c ||
               newControlledDocument.Current_Region_auto__c != oldCDocs.get(newControlledDocument.Id).Current_Region_auto__c ||
               newControlledDocument.Current_Organization_Acronym__c != oldCDocs.get(newControlledDocument.Id).Current_Organization_Acronym__c ||
               newControlledDocument.Current_Division_Name__c != oldCDocs.get(newControlledDocument.Id).Current_Division_Name__c ||
               newControlledDocument.Current_Division_Code__c != oldCDocs.get(newControlledDocument.Id).Current_Division_Code__c ||
               newControlledDocument.Current_Region__c != oldCDocs.get(newControlledDocument.Id).Current_Region__c){

                cDocsNeedingHistoryChanges.add(newControlledDocument);
                newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
                newControlledDocument.Days_In_Current_Location_New__c = 0;
                added = true;
            }
            // adds a new record even if the location doesn't change
            if(newControlledDocument.Stage__c != oldCDocs.get(newControlledDocument.Id).Stage__c ||
               newControlledDocument.OMB__c != oldCDocs.get(newControlledDocument.Id).OMB__c){

                newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;
                newControlledDocument.Days_On_Current_Stage_New__c = 0;
                if(!added){
                    cDocsNeedingHistoryChanges.add(newControlledDocument);
                    added = true;
                    if(newControlledDocument.Stage__c == 'Closed'){
                        controlledDocumentIdRecursionTracker.put(newControlledDocument.Id, true);
                    }
                }
            }

            // if these dates change then either an admin is doing something or we are testing
            boolean stageStartDateChanged = false;
            if(newControlledDocument.Current_Stage_Start_Date_New__c != oldCDocs.get(newControlledDocument.Id).Current_Stage_Start_Date_New__c){
                stageStartDateChanged = true;
            }

            // if these dates change then either an admin is doing something or we are testing
            boolean locationStartDateChanged = false;
            if(newControlledDocument.Current_Location_Start_Date_New__c != oldCDocs.get(newControlledDocument.Id).Current_Stage_Start_Date_New__c){
                locationStartDateChanged = true;
            }

            // changes controlled documents whenever the batch is run and not any other time
            if(UpdateDaysOpenOnApprovalStepsBatch.isBatchOn || stageStartDateChanged || locationStartDateChanged){
                newControlledDocument.Days_On_Current_Stage_New__c = getBsnsHoursDifferenceLong(cdtBusinessHours, newControlledDocument.Current_Stage_Start_Date_New__c, currentLocalDate);
                newControlledDocument.Days_In_Current_Location_New__c = getBsnsHoursDifferenceLong(cdtBusinessHours, newControlledDocument.Current_Location_Start_Date_New__c, currentLocalDate);
            }
        }

        List<Id> controlledDocumentIds = new List<Id>();
        List<Location_and_Stage_History__c> historiesToAdd = new List<Location_and_Stage_History__c>();
        for(Controlled_Document__c controlledDocument : cDocsNeedingHistoryChanges){

            controlledDocumentIds.add(controlledDocument.Id);

            // if closed we are not adding a new Location and Stage History but updating the most recent one to inactive and setting the end date
            if(controlledDocument.Stage__c == 'Closed') continue;

            Location_and_Stage_History__c newHistoryLocation = new Location_and_Stage_History__c();
            newHistoryLocation.Name = controlledDocument.Current_Location_auto__c;           

            // Case# 30668 - BEGIN
            // String locationName = (controlledDocument.current_Region__c != null) ? mergeString(controlledDocument.current_Region__c, 
            //                                                                                 controlledDocument.Current_Location__c) : null;
            // newHistoryLocation.Name = (locationName != null) ? locationName : controlledDocument.Current_Location__c;
            // Case# 30668 - END

            newHistoryLocation.Stage__c = controlledDocument.Stage__c;
            newHistoryLocation.Active__c = TRUE;
            newHistoryLocation.Start_Date__c = currentLocal;

            newHistoryLocation.Controlled_Document__c = controlledDocument.Id;
            newHistoryLocation.Of_Days_New__c = 0.0;
            
            if (controlledDocument.Stage__c == 'Closed'){
                newHistoryLocation.End_Date__c = currentLocal;              
            }
            
            newHistoryLocation.Name = String.isNotBlank(controlledDocument.Current_Location_auto__c) ? controlledDocument.Current_Location_auto__c : '';
            newHistoryLocation.Region__c = String.isNotBlank(controlledDocument.Current_Region_Auto__c) ? ControlledDocument.Current_Region_Auto__c : '';   
            newHistoryLocation.Organization_Acronym__c = String.isNotBlank(controlledDocument.Current_Organization_Acronym__c) ? ControlledDocument.Current_Organization_Acronym__c : '';    
            newHistoryLocation.Division_Code__c = String.isNotBlank(controlledDocument.Current_Division_Code__c) ? ControlledDocument.Current_Division_Code__c : '';  
            newHistoryLocation.Division_Name__c = String.isNotBlank(controlledDocument.Current_Division_Name__c) ? ControlledDocument.Current_Division_Name__c : '';                  

            historiesToAdd.add(newHistoryLocation);
        }

        List<Location_and_Stage_History__c> oldHistoryList = [SELECT Id, Active__c, Start_Date__c, End_Date__c, of_Days_New__c
                                                    FROM Location_and_Stage_History__c
                                                    WHERE Active__c = true AND
                                                        Controlled_Document__c IN :controlledDocumentIds];                          

        for(Location_and_Stage_History__c oldHistory : oldHistoryList){
            oldHistory.Active__c = FALSE;
            oldHistory.End_Date__c = currentLocal;
            if(oldHistory.Start_Date__c != null) {
                Double d = getBsnsHoursDifferenceDouble(cdtBusinessHours, oldHistory.Start_Date__c, oldHistory.End_Date__c);
                oldHistory.of_Days_New__c = d;
            }
        }

        update oldHistoryList;
        insert historiesToAdd;
    }

    private static Long getBsnsHoursDifferenceLong(BusinessHours bsnsHours, Datetime startTime, Datetime endTime){
        Long l = BusinessHours.diff(bsnsHours.Id, startTime, endTime);
        return l/1000/3600/8;
    }

    private static Double getBsnsHoursDifferenceDouble(BusinessHours bsnsHours, Datetime startTime, Datetime endTime){
        Double d = BusinessHours.diff(bsnsHours.Id, startTime, endTime);
        return d/1000/3600/8;
    }
 /*   // Case# 30668 - BEGIN 
    private static String mergeString(String currentRegion, String currentLocation) {
        String merged = null;
        if(currentregion != null) {
            merged = currentRegion + ': ' + currentLocation;
            if(merged.length() > 80) {
                merged = merged.substring(0, 80);
            }
        }
        return merged;
    } // Case# 30668 - END
*/

}